#!/usr/bin/env python3
"""Generate Italian translations for D&D 3.5 SRD spells."""

import json
import os

# School translations
SCHOOL_MAP = {
    "Abjuration": "Abiurazione",
    "Conjuration": "Evocazione",
    "Divination": "Divinazione",
    "Enchantment": "Ammaliamento",
    "Evocation": "Invocazione",
    "Illusion": "Illusione",
    "Necromancy": "Necromanzia",
    "Transmutation": "Trasmutazione",
    "Universal": "Universale",
}

# Subschool translations
SUBSCHOOL_MAP = {
    "Calling": "Richiamo",
    "Creation": "Creazione",
    "Healing": "Guarigione",
    "Summoning": "Convocazione",
    "Teleportation": "Teletrasporto",
    "Charm": "Charme",
    "Compulsion": "Compulsione",
    "Figment": "Finzione",
    "Glamer": "Mascheramento",
    "Pattern": "Trama",
    "Phantasm": "Fantasma",
    "Shadow": "Ombra",
    "Scrying": "Scrutamento",
    "Creation or Calling": "Creazione o Richiamo",
    "Figment, Glamer": "Finzione, Mascheramento",
}

# Complete spell name translations (official Italian D&D 3.5 PHB/SRD)
NAME_MAP = {
    "Acid Arrow": "Freccia Acida",
    "Acid Fog": "Nebbia Acida",
    "Acid Splash": "Spruzzo Acido",
    "Aid": "Aiuto",
    "Air Walk": "Camminare nell'Aria",
    "Alarm": "Allarme",
    "Align Weapon": "Allineare Arma",
    "Alter Self": "Alterare Se Stesso",
    "Analyze Dweomer": "Analizzare Incantesimo",
    "Animal Growth": "Crescita Animale",
    "Animal Messenger": "Messaggero Animale",
    "Animal Shapes": "Forme Animali",
    "Animal Trance": "Trance Animale",
    "Animate Dead": "Animare Morti",
    "Animate Objects": "Animare Oggetti",
    "Animate Plants": "Animare Piante",
    "Animate Rope": "Animare Corde",
    "Antilife Shell": "Guscio Anti-Vita",
    "Antimagic Field": "Campo Anti-Magia",
    "Antipathy": "Antipatia",
    "Antiplant Shell": "Guscio Anti-Piante",
    "Arcane Eye": "Occhio Arcano",
    "Arcane Lock": "Serratura Arcana",
    "Arcane Mark": "Marchio Arcano",
    "Arcane Sight": "Vista Arcana",
    "Arcane Sight, Greater": "Vista Arcana Superiore",
    "Astral Projection": "Proiezione Astrale",
    "Atonement": "Espiazione",
    "Augury": "Augurio",
    "Awaken": "Risveglio",
    "Baleful Polymorph": "Metamorfosi Funesta",
    "Bane": "Anatema",
    "Banishment": "Bandire",
    "Barkskin": "Pelle Coriacea",
    "Bear's Endurance": "Resistenza dell'Orso",
    "Bear's Endurance, Mass": "Resistenza dell'Orso di Massa",
    "Bestow Curse": "Infliggere Maledizione",
    "Binding": "Vincolo",
    "Black Tentacles": "Tentacoli Neri",
    "Blade Barrier": "Barriera di Lame",
    "Blasphemy": "Blasfemia",
    "Bless": "Benedizione",
    "Bless Water": "Benedire Acqua",
    "Bless Weapon": "Benedire Arma",
    "Blight": "Rovinare",
    "Blindness/Deafness": "Cecità/Sordità",
    "Blink": "Intermittenza",
    "Blur": "Sfocatura",
    "Break Enchantment": "Spezzare Incantamento",
    "Bull's Strength": "Forza del Toro",
    "Bull's Strength, Mass": "Forza del Toro di Massa",
    "Burning Hands": "Mani Brucianti",
    "Call Lightning": "Invocare il Fulmine",
    "Call Lightning Storm": "Invocare Tempesta di Fulmini",
    "Calm Animals": "Calmare Animali",
    "Calm Emotions": "Calmare Emozioni",
    "Cat's Grace": "Grazia del Gatto",
    "Cat's Grace, Mass": "Grazia del Gatto di Massa",
    "Cause Fear": "Causare Paura",
    "Chain Lightning": "Fulmine a Catena",
    "Changestaff": "Bastone Mutaforma",
    "Chaos Hammer": "Martello del Caos",
    "Charm Animal": "Ammaliare Animali",
    "Charm Monster": "Ammaliare Mostri",
    "Charm Monster, Mass": "Ammaliare Mostri di Massa",
    "Charm Person": "Ammaliare Persone",
    "Chill Metal": "Metallo Gelido",
    "Chill Touch": "Tocco Gelido",
    "Circle of Death": "Cerchio di Morte",
    "Clairaudience/Clairvoyance": "Chiaroudienza/Chiaroveggenza",
    "Clenched Fist": "Pugno Serrato",
    "Cloak of Chaos": "Manto del Caos",
    "Clone": "Clone",
    "Cloudkill": "Nube Mortale",
    "Color Spray": "Spruzzo di Colori",
    "Command": "Comando",
    "Command, Greater": "Comando Superiore",
    "Command Plants": "Comandare Piante",
    "Command Undead": "Comandare Non Morti",
    "Commune": "Comunione",
    "Commune with Nature": "Comunione con la Natura",
    "Comprehend Languages": "Comprensione dei Linguaggi",
    "Cone of Cold": "Cono di Freddo",
    "Confusion": "Confusione",
    "Confusion, Lesser": "Confusione Minore",
    "Consecrate": "Consacrare",
    "Contact Other Plane": "Contattare Altri Piani",
    "Contagion": "Contagio",
    "Contingency": "Contingenza",
    "Continual Flame": "Fiamma Perenne",
    "Control Plants": "Controllare Piante",
    "Control Undead": "Controllare Non Morti",
    "Control Water": "Controllare Acqua",
    "Control Weather": "Controllare Tempo Atmosferico",
    "Control Winds": "Controllare Venti",
    "Create Food and Water": "Creare Cibo e Acqua",
    "Create Greater Undead": "Creare Non Morti Superiori",
    "Create Undead": "Creare Non Morti",
    "Create Water": "Creare Acqua",
    "Creeping Doom": "Rovina Strisciante",
    "Crushing Despair": "Disperazione Opprimente",
    "Crushing Hand": "Mano Stringente",
    "Cure Critical Wounds": "Cura Ferite Critiche",
    "Cure Critical Wounds, Mass": "Cura Ferite Critiche di Massa",
    "Cure Light Wounds": "Cura Ferite Leggere",
    "Cure Light Wounds, Mass": "Cura Ferite Leggere di Massa",
    "Cure Minor Wounds": "Cura Ferite Minori",
    "Cure Moderate Wounds": "Cura Ferite Moderate",
    "Cure Moderate Wounds, Mass": "Cura Ferite Moderate di Massa",
    "Cure Serious Wounds": "Cura Ferite Gravi",
    "Cure Serious Wounds, Mass": "Cura Ferite Gravi di Massa",
    "Curse Water": "Maledire l'Acqua",
    "Dancing Lights": "Luci Danzanti",
    "Darkness": "Oscurità",
    "Darkvision": "Scurovisione",
    "Daylight": "Luce del Giorno",
    "Daze": "Frastornare",
    "Daze Monster": "Frastornare Mostri",
    "Death Knell": "Campana a Morto",
    "Death Ward": "Interdizione alla Morte",
    "Deathwatch": "Veglia Funebre",
    "Deep Slumber": "Sonno Profondo",
    "Deeper Darkness": "Oscurità Profonda",
    "Delay Poison": "Ritardare Veleno",
    "Delayed Blast Fireball": "Palla di Fuoco a Scoppio Ritardato",
    "Demand": "Esigere",
    "Desecrate": "Dissacrare",
    "Destruction": "Distruzione",
    "Detect Animals or Plants": "Individuare Animali o Piante",
    "Detect Chaos": "Individuare il Caos",
    "Detect Evil": "Individuare il Male",
    "Detect Good": "Individuare il Bene",
    "Detect Law": "Individuare la Legge",
    "Detect Magic": "Individuare il Magico",
    "Detect Poison": "Individuare Veleni",
    "Detect Scrying": "Individuare Scrutamento",
    "Detect Secret Doors": "Individuare Porte Segrete",
    "Detect Snares and Pits": "Individuare Trappole e Fosse",
    "Detect Thoughts": "Individuare Pensieri",
    "Detect Undead": "Individuare Non Morti",
    "Dictum": "Editto",
    "Dimension Door": "Porta Dimensionale",
    "Dimensional Anchor": "Ancora Dimensionale",
    "Dimensional Lock": "Blocco Dimensionale",
    "Diminish Plants": "Rimpicciolire Piante",
    "Discern Lies": "Discernere Bugie",
    "Discern Location": "Discernere Posizione",
    "Disguise Self": "Camuffare Se Stesso",
    "Disintegrate": "Disintegrazione",
    "Dismissal": "Congedo",
    "Dispel Chaos": "Dissolvi il Caos",
    "Dispel Evil": "Dissolvi il Male",
    "Dispel Good": "Dissolvi il Bene",
    "Dispel Law": "Dissolvi la Legge",
    "Dispel Magic": "Dissolvi Magie",
    "Dispel Magic, Greater": "Dissolvi Magie Superiore",
    "Displacement": "Dislocazione",
    "Disrupt Undead": "Distruggere Non Morti",
    "Disrupting Weapon": "Arma Distruttiva",
    "Divination": "Divinazione",
    "Divine Favor": "Favore Divino",
    "Divine Power": "Potere Divino",
    "Dominate Animal": "Dominare Animali",
    "Dominate Monster": "Dominare Mostri",
    "Dominate Person": "Dominare Persone",
    "Doom": "Giudizio",
    "Dream": "Sogno",
    "Eagle's Splendor": "Splendore dell'Aquila",
    "Eagle's Splendor, Mass": "Splendore dell'Aquila di Massa",
    "Earthquake": "Terremoto",
    "Elemental Swarm": "Sciame Elementale",
    "Endure Elements": "Sopportare Elementi",
    "Energy Drain": "Risucchio di Energia",
    "Enervation": "Enervazione",
    "Enlarge Person": "Ingrandire Persone",
    "Enlarge Person, Mass": "Ingrandire Persone di Massa",
    "Entangle": "Intralciare",
    "Enthrall": "Affascinare",
    "Entropic Shield": "Scudo Entropico",
    "Erase": "Cancellare",
    "Ethereal Jaunt": "Escursione Eterea",
    "Etherealness": "Forma Eterea",
    "Expeditious Retreat": "Ritirata Rapida",
    "Explosive Runes": "Rune Esplosive",
    "Eyebite": "Malocchio",
    "Fabricate": "Fabbricare",
    "Faerie Fire": "Fuoco Fatuo",
    "False Life": "Vita Falsata",
    "False Vision": "Visione Falsa",
    "Fear": "Paura",
    "Feather Fall": "Caduta Morbida",
    "Feeblemind": "Demenza",
    "Find the Path": "Trovare il Sentiero",
    "Find Traps": "Trovare Trappole",
    "Finger of Death": "Dito della Morte",
    "Fire Seeds": "Semi di Fuoco",
    "Fire Shield": "Scudo di Fuoco",
    "Fire Storm": "Tempesta di Fuoco",
    "Fire Trap": "Trappola di Fuoco",
    "Fireball": "Palla di Fuoco",
    "Flame Arrow": "Freccia Infuocata",
    "Flame Blade": "Lama di Fuoco",
    "Flame Strike": "Colonna di Fuoco",
    "Flaming Sphere": "Sfera Infuocata",
    "Flare": "Bagliore",
    "Flesh to Stone": "Carne in Pietra",
    "Fly": "Volare",
    "Floating Disk": "Disco Fluttuante",
    "Fog Cloud": "Nube di Nebbia",
    "Forbiddance": "Interdizione",
    "Forcecage": "Gabbia di Forza",
    "Forceful Hand": "Mano Possente",
    "Foresight": "Preveggenza",
    "Fox's Cunning": "Astuzia della Volpe",
    "Fox's Cunning, Mass": "Astuzia della Volpe di Massa",
    "Freedom": "Libertà",
    "Freedom of Movement": "Libertà di Movimento",
    "Freezing Sphere": "Sfera Gelata",
    "Gaseous Form": "Forma Gassosa",
    "Gate": "Portale",
    "Geas/Quest": "Missione",
    "Geas, Lesser": "Missione Minore",
    "Gentle Repose": "Riposo Inviolato",
    "Ghost Sound": "Suono Fantasma",
    "Ghoul Touch": "Tocco del Ghoul",
    "Giant Vermin": "Parassiti Giganti",
    "Glibness": "Eloquenza",
    "Glitterdust": "Polvere Scintillante",
    "Globe of Invulnerability": "Globo di Invulnerabilità",
    "Globe of Invulnerability, Lesser": "Globo di Invulnerabilità Minore",
    "Glyph of Warding": "Glifo di Interdizione",
    "Glyph of Warding, Greater": "Glifo di Interdizione Superiore",
    "Goodberry": "Bacche Benefiche",
    "Good Hope": "Buona Speranza",
    "Grasping Hand": "Mano Afferrante",
    "Grease": "Unto",
    "Greater (Spell Name)": "Superiore (Nome Incantesimo)",
    "Guards and Wards": "Guardie e Interdizioni",
    "Guidance": "Guida",
    "Gust of Wind": "Raffica di Vento",
    "Hallow": "Consacrare Luogo",
    "Hallucinatory Terrain": "Terreno Illusorio",
    "Halt Undead": "Fermare Non Morti",
    "Harm": "Infliggere Ferite",
    "Haste": "Velocità",
    "Heal": "Guarigione",
    "Heal, Mass": "Guarigione di Massa",
    "Heal Mount": "Guarire Cavalcatura",
    "Heat Metal": "Metallo Rovente",
    "Helping Hand": "Mano Soccorritrice",
    "Heroes' Feast": "Banchetto degli Eroi",
    "Heroism": "Eroismo",
    "Heroism, Greater": "Eroismo Superiore",
    "Hide From Animals": "Nascondersi dagli Animali",
    "Hide From Undead": "Nascondersi dai Non Morti",
    "Hideous Laughter": "Risata Incontenibile",
    "Hold Animal": "Bloccare Animali",
    "Hold Monster": "Bloccare Mostri",
    "Hold Monster, Mass": "Bloccare Mostri di Massa",
    "Hold Person": "Bloccare Persone",
    "Hold Person, Mass": "Bloccare Persone di Massa",
    "Hold Portal": "Bloccare Portale",
    "Holy Aura": "Aura Sacra",
    "Holy Smite": "Punizione Sacra",
    "Holy Sword": "Spada Sacra",
    "Holy Word": "Parola Sacra",
    "Horrid Wilting": "Avvizzire Orribile",
    "Hypnotic Pattern": "Trama Ipnotica",
    "Hypnotism": "Ipnotismo",
    "Ice Storm": "Tempesta di Ghiaccio",
    "Identify": "Identificare",
    "Illusory Script": "Scrittura Illusoria",
    "Illusory Wall": "Muro Illusorio",
    "Imbue with Spell Ability": "Investire di Capacità Magica",
    "Implosion": "Implosione",
    "Imprisonment": "Imprigionamento",
    "Incendiary Cloud": "Nube Incendiaria",
    "Inflict Critical Wounds": "Infliggere Ferite Critiche",
    "Inflict Critical Wounds, Mass": "Infliggere Ferite Critiche di Massa",
    "Inflict Light Wounds": "Infliggere Ferite Leggere",
    "Inflict Light Wounds, Mass": "Infliggere Ferite Leggere di Massa",
    "Inflict Minor Wounds": "Infliggere Ferite Minori",
    "Inflict Moderate Wounds": "Infliggere Ferite Moderate",
    "Inflict Moderate Wounds, Mass": "Infliggere Ferite Moderate di Massa",
    "Inflict Serious Wounds": "Infliggere Ferite Gravi",
    "Inflict Serious Wounds, Mass": "Infliggere Ferite Gravi di Massa",
    "Insanity": "Follia",
    "Insect Plague": "Piaga degli Insetti",
    "Instant Summons": "Evocazione Istantanea",
    "Interposing Hand": "Mano Interponente",
    "Invisibility": "Invisibilità",
    "Invisibility, Greater": "Invisibilità Superiore",
    "Invisibility, Mass": "Invisibilità di Massa",
    "Invisibility Purge": "Epurazione dell'Invisibilità",
    "Invisibility Sphere": "Sfera di Invisibilità",
    "Iron Body": "Corpo di Ferro",
    "Ironwood": "Legno di Ferro",
    "Irresistible Dance": "Danza Irresistibile",
    "Jump": "Saltare",
    "Keen Edge": "Lama Affilata",
    "Knock": "Scassinare",
    "Know Direction": "Conoscere Direzione",
    "Legend Lore": "Conoscenze delle Leggende",
    "Lesser (Spell Name)": "Minore (Nome Incantesimo)",
    "Levitate": "Levitare",
    "Light": "Luce",
    "Lightning Bolt": "Fulmine",
    "Limited Wish": "Desiderio Limitato",
    "Liveoak": "Quercia Vivente",
    "Locate Creature": "Localizzare Creature",
    "Locate Object": "Localizzare Oggetto",
    "Longstrider": "Passo Lungo",
    "Lullaby": "Ninnananna",
    "Mage Armor": "Armatura del Mago",
    "Mage Hand": "Mano del Mago",
    "Mage's Disjunction": "Disgiunzione del Mago",
    "Mage's Faithful Hound": "Segugio Fedele del Mago",
    "Mage's Lucubration": "Lucubrazione del Mago",
    "Mage's Magnificent Mansion": "Magione Magnifica del Mago",
    "Mage's Private Sanctum": "Santuario Privato del Mago",
    "Mage's Sword": "Spada del Mago",
    "Magic Aura": "Aura Magica",
    "Magic Circle Against Chaos": "Cerchio Magico Contro il Caos",
    "Magic Circle Against Evil": "Cerchio Magico Contro il Male",
    "Magic Circle Against Good": "Cerchio Magico Contro il Bene",
    "Magic Circle Against Law": "Cerchio Magico Contro la Legge",
    "Magic Fang": "Zanna Magica",
    "Magic Fang, Greater": "Zanna Magica Superiore",
    "Magic Jar": "Giara Magica",
    "Magic Missile": "Dardo Incantato",
    "Magic Mouth": "Bocca Magica",
    "Magic Stone": "Pietra Magica",
    "Magic Vestment": "Veste Magica",
    "Magic Weapon": "Arma Magica",
    "Magic Weapon, Greater": "Arma Magica Superiore",
    "Major Creation": "Creazione Maggiore",
    "Major Image": "Immagine Maggiore",
    "Make Whole": "Riparare Integralmente",
    "Mark of Justice": "Marchio di Giustizia",
    "Mass (Spell Name)": "Di Massa (Nome Incantesimo)",
    "Maze": "Labirinto",
    "Meld Into Stone": "Fondersi nella Pietra",
    "Mending": "Riparare",
    "Message": "Messaggio",
    "Meteor Swarm": "Sciame di Meteore",
    "Mind Blank": "Vuoto Mentale",
    "Mind Fog": "Nebbia della Mente",
    "Minor Creation": "Creazione Minore",
    "Minor Image": "Immagine Minore",
    "Miracle": "Miracolo",
    "Mirage Arcana": "Miraggio Arcano",
    "Mirror Image": "Immagine Speculare",
    "Misdirection": "Depistaggio",
    "Mislead": "Fuorviare",
    "Mnemonic Enhancer": "Potenziatore Mnemonico",
    "Modify Memory": "Modificare Memoria",
    "Moment of Prescience": "Momento di Prescienza",
    "Mount": "Cavalcatura",
    "Move Earth": "Muovere Terra",
    "Neutralize Poison": "Neutralizzare Veleno",
    "Nightmare": "Incubo",
    "Nondetection": "Non Individuazione",
    "Obscure Object": "Oscurare Oggetto",
    "Obscuring Mist": "Foschia Oscurante",
    "Open/Close": "Aprire/Chiudere",
    "Order's Wrath": "Collera dell'Ordine",
    "Overland Flight": "Volo Prolungato",
    "Owl's Wisdom": "Saggezza del Gufo",
    "Owl's Wisdom, Mass": "Saggezza del Gufo di Massa",
    "Passwall": "Passapareti",
    "Pass Without Trace": "Passare Senza Tracce",
    "Permanency": "Permanenza",
    "Permanent Image": "Immagine Permanente",
    "Persistent Image": "Immagine Persistente",
    "Phantasmal Killer": "Assassino Fantasma",
    "Phantom Steed": "Destriero Fantasma",
    "Phantom Trap": "Trappola Fantasma",
    "Phase Door": "Porta in Fase",
    "Planar Ally": "Alleato Planare",
    "Planar Ally, Greater": "Alleato Planare Superiore",
    "Planar Ally, Lesser": "Alleato Planare Minore",
    "Planar Binding": "Vincolo Planare",
    "Planar Binding, Greater": "Vincolo Planare Superiore",
    "Planar Binding, Lesser": "Vincolo Planare Minore",
    "Plane Shift": "Spostamento Planare",
    "Plant Growth": "Crescita Vegetale",
    "Poison": "Veleno",
    "Polar Ray": "Raggio Polare",
    "Polymorph": "Metamorfosi",
    "Polymorph Any Object": "Metamorfosi Universale",
    "Power Word Blind": "Parola del Potere Accecare",
    "Power Word Kill": "Parola del Potere Uccidere",
    "Power Word Stun": "Parola del Potere Stordire",
    "Prayer": "Preghiera",
    "Prestidigitation": "Prestidigitazione",
    "Prismatic Sphere": "Sfera Prismatica",
    "Prismatic Spray": "Spruzzo Prismatico",
    "Prismatic Wall": "Muro Prismatico",
    "Produce Flame": "Produrre Fiamma",
    "Programmed Image": "Immagine Programmata",
    "Project Image": "Proiettare Immagine",
    "Protection From Arrows": "Protezione dalle Frecce",
    "Protection From Chaos": "Protezione dal Caos",
    "Protection From Energy": "Protezione dall'Energia",
    "Protection From Evil": "Protezione dal Male",
    "Protection From Good": "Protezione dal Bene",
    "Protection From Law": "Protezione dalla Legge",
    "Protection From Spells": "Protezione dagli Incantesimi",
    "Prying Eyes": "Occhi Indiscreti",
    "Prying Eyes, Greater": "Occhi Indiscreti Superiori",
    "Purify Food and Drink": "Purificare Cibo e Bevande",
    "Pyrotechnics": "Pirotecnica",
    "Quench": "Estinguere",
    "Rage": "Furia",
    "Rainbow Pattern": "Trama dell'Arcobaleno",
    "Raise Dead": "Rianimare Morti",
    "Ray of Enfeeblement": "Raggio di Indebolimento",
    "Ray of Exhaustion": "Raggio di Esaurimento",
    "Ray of Frost": "Raggio di Gelo",
    "Read Magic": "Lettura del Magico",
    "Reduce Animal": "Ridurre Animali",
    "Reduce Person": "Ridurre Persone",
    "Reduce Person, Mass": "Ridurre Persone di Massa",
    "Refuge": "Rifugio",
    "Regenerate": "Rigenerazione",
    "Reincarnate": "Reincarnazione",
    "Remove Blindness/Deafness": "Rimuovere Cecità/Sordità",
    "Remove Curse": "Rimuovere Maledizione",
    "Remove Disease": "Rimuovere Malattia",
    "Remove Fear": "Rimuovere Paura",
    "Remove Paralysis": "Rimuovere Paralisi",
    "Repel Metal or Stone": "Respingere Metallo o Pietra",
    "Repel Vermin": "Respingere Parassiti",
    "Repel Wood": "Respingere Legno",
    "Repulsion": "Repulsione",
    "Resilient Sphere": "Sfera Resiliente",
    "Resistance": "Resistenza",
    "Resist Energy": "Resistere all'Energia",
    "Restoration": "Ristorare",
    "Restoration, Greater": "Ristorare Superiore",
    "Restoration, Lesser": "Ristorare Minore",
    "Resurrection": "Resurrezione",
    "Reverse Gravity": "Invertire Gravità",
    "Righteous Might": "Potere Rettitudine",
    "Rope Trick": "Trucco della Corda",
    "Rusting Grasp": "Presa Arrugginente",
    "Sanctuary": "Santuario",
    "Scare": "Spaventare",
    "Scintillating Pattern": "Trama Scintillante",
    "Scorching Ray": "Raggio Rovente",
    "Screen": "Schermo",
    "Scrying": "Scrutare",
    "Scrying, Greater": "Scrutare Superiore",
    "Sculpt Sound": "Plasmare Suoni",
    "Searing Light": "Luce Incandescente",
    "Secret Chest": "Scrigno Segreto",
    "Secret Page": "Pagina Segreta",
    "Secure Shelter": "Rifugio Sicuro",
    "See Invisibility": "Vedere Invisibilità",
    "Seeming": "Parvenza",
    "Sending": "Invio",
    "Sepia Snake Sigil": "Sigillo del Serpente Color Seppia",
    "Sequester": "Sequestrare",
    "Shades": "Ombre",
    "Shadow Conjuration": "Evocazione d'Ombra",
    "Shadow Conjuration, Greater": "Evocazione d'Ombra Superiore",
    "Shadow Evocation": "Invocazione d'Ombra",
    "Shadow Evocation, Greater": "Invocazione d'Ombra Superiore",
    "Shadow Walk": "Camminata nell'Ombra",
    "Shambler": "Cumulo Strisciante",
    "Shapechange": "Cambiare Forma",
    "Shatter": "Frantumare",
    "Shield": "Scudo",
    "Shield of Faith": "Scudo della Fede",
    "Shield of Law": "Scudo della Legge",
    "Shield Other": "Scudo su Altro",
    "Shillelagh": "Shillelagh",
    "Shocking Grasp": "Tocco Shocking",
    "Shout": "Urlo",
    "Shout, Greater": "Urlo Superiore",
    "Shrink Item": "Rimpicciolire Oggetto",
    "Silence": "Silenzio",
    "Silent Image": "Immagine Silenziosa",
    "Simulacrum": "Simulacro",
    "Slay Living": "Uccidere Viventi",
    "Sleep": "Sonno",
    "Sleet Storm": "Tempesta di Nevischio",
    "Slow": "Lentezza",
    "Snare": "Laccio",
    "Soften Earth and Stone": "Ammorbidire Terra e Pietra",
    "Solid Fog": "Nebbia Solida",
    "Song of Discord": "Canto di Discordia",
    "Soul Bind": "Vincolo dell'Anima",
    "Sound Burst": "Scoppio Sonoro",
    "Speak with Animals": "Parlare con gli Animali",
    "Speak with Dead": "Parlare con i Morti",
    "Speak with Plants": "Parlare con le Piante",
    "Spectral Hand": "Mano Spettrale",
    "Spell Immunity": "Immunità agli Incantesimi",
    "Spell Immunity, Greater": "Immunità agli Incantesimi Superiore",
    "Spell Resistance": "Resistenza agli Incantesimi",
    "Spellstaff": "Bastone Magico",
    "Spell Turning": "Rivoltare Incantesimi",
    "Spider Climb": "Scalare Ragno",
    "Spike Growth": "Crescita di Spine",
    "Spike Stones": "Pietre Acuminate",
    "Spiritual Weapon": "Arma Spirituale",
    "Statue": "Statua",
    "Status": "Status",
    "Stinking Cloud": "Nube Maleodorante",
    "Stone Shape": "Scolpire Pietra",
    "Stoneskin": "Pelle di Pietra",
    "Stone Tell": "Pietra Parlante",
    "Stone to Flesh": "Pietra in Carne",
    "Storm of Vengeance": "Tempesta di Vendetta",
    "Suggestion": "Suggestione",
    "Suggestion, Mass": "Suggestione di Massa",
    "Summon Instrument": "Evocare Strumento",
    "Summon Monster I": "Evocare Mostri I",
    "Summon Monster II": "Evocare Mostri II",
    "Summon Monster III": "Evocare Mostri III",
    "Summon Monster IV": "Evocare Mostri IV",
    "Summon Monster V": "Evocare Mostri V",
    "Summon Monster VI": "Evocare Mostri VI",
    "Summon Monster VII": "Evocare Mostri VII",
    "Summon Monster VIII": "Evocare Mostri VIII",
    "Summon Monster IX": "Evocare Mostri IX",
    "Summon Nature's Ally I": "Evocare Alleato Naturale I",
    "Summon Nature's Ally II": "Evocare Alleato Naturale II",
    "Summon Nature's Ally III": "Evocare Alleato Naturale III",
    "Summon Nature's Ally IV": "Evocare Alleato Naturale IV",
    "Summon Nature's Ally V": "Evocare Alleato Naturale V",
    "Summon Nature's Ally VI": "Evocare Alleato Naturale VI",
    "Summon Nature's Ally VII": "Evocare Alleato Naturale VII",
    "Summon Nature's Ally VIII": "Evocare Alleato Naturale VIII",
    "Summon Nature's Ally IX": "Evocare Alleato Naturale IX",
    "Summon Swarm": "Evocare Sciame",
    "Sunbeam": "Raggio di Sole",
    "Sunburst": "Esplosione Solare",
    "Symbol of Death": "Simbolo di Morte",
    "Symbol of Fear": "Simbolo di Paura",
    "Symbol of Insanity": "Simbolo di Follia",
    "Symbol of Pain": "Simbolo di Dolore",
    "Symbol of Persuasion": "Simbolo di Persuasione",
    "Symbol of Sleep": "Simbolo di Sonno",
    "Symbol of Stunning": "Simbolo di Stordimento",
    "Symbol of Weakness": "Simbolo di Debolezza",
    "Sympathetic Vibration": "Vibrazione Simpatica",
    "Sympathy": "Simpatia",
    "Telekinesis": "Telecinesi",
    "Telekinetic Sphere": "Sfera Telecinetica",
    "Telepathic Bond": "Legame Telepatico",
    "Teleport": "Teletrasporto",
    "Teleport Object": "Teletrasporto di Oggetti",
    "Teleport, Greater": "Teletrasporto Superiore",
    "Teleportation Circle": "Cerchio di Teletrasporto",
    "Temporal Stasis": "Stasi Temporale",
    "Time Stop": "Fermare il Tempo",
    "Tiny Hut": "Capanna",
    "Tongues": "Linguaggi",
    "Touch of Fatigue": "Tocco di Fatica",
    "Touch of Idiocy": "Tocco di Idiozia",
    "Transformation": "Trasformazione",
    "Transmute Metal to Wood": "Trasmutare Metallo in Legno",
    "Transmute Mud to Rock": "Trasmutare Fango in Roccia",
    "Transmute Rock to Mud": "Trasmutare Roccia in Fango",
    "Transport via Plants": "Trasporto tramite Piante",
    "Trap the Soul": "Intrappolare l'Anima",
    "Tree Shape": "Forma di Albero",
    "Tree Stride": "Passo dell'Albero",
    "True Resurrection": "Resurrezione Pura",
    "True Seeing": "Vista del Vero",
    "True Strike": "Colpo Sicuro",
    "Undeath to Death": "Non Morte in Morte",
    "Undetectable Alignment": "Allineamento Non Individuabile",
    "Unhallow": "Dissacrare Luogo",
    "Unholy Aura": "Aura Empia",
    "Unholy Blight": "Punizione Empia",
    "Unseen Servant": "Servitore Invisibile",
    "Vampiric Touch": "Tocco del Vampiro",
    "Veil": "Velo",
    "Ventriloquism": "Ventriloquio",
    "Virtue": "Virtù",
    "Vision": "Visione",
    "Wail of the Banshee": "Lamento della Banshee",
    "Wall of Fire": "Muro di Fuoco",
    "Wall of Force": "Muro di Forza",
    "Wall of Ice": "Muro di Ghiaccio",
    "Wall of Iron": "Muro di Ferro",
    "Wall of Stone": "Muro di Pietra",
    "Wall of Thorns": "Muro di Spine",
    "Warp Wood": "Deformare Legno",
    "Water Breathing": "Respirare sott'Acqua",
    "Water Walk": "Camminare sull'Acqua",
    "Waves of Exhaustion": "Onde di Esaurimento",
    "Waves of Fatigue": "Onde di Fatica",
    "Web": "Ragnatela",
    "Weird": "Destino",
    "Whirlwind": "Turbine",
    "Whispering Wind": "Vento Sussurrante",
    "Wind Walk": "Camminata nel Vento",
    "Wind Wall": "Muro di Vento",
    "Wish": "Desiderio",
    "Wood Shape": "Plasmare Legno",
    "Word of Chaos": "Parola del Caos",
    "Word of Recall": "Parola del Richiamo",
    "Zone of Silence": "Zona di Silenzio",
    "Zone of Truth": "Zona di Verità",
}


def translate_school(school_en):
    """Translate a school name, handling malformed entries."""
    if school_en in SCHOOL_MAP:
        return SCHOOL_MAP[school_en]
    # Meta-entries (greater, lesser, mass) have long descriptive text as school
    # Return a generic label for these
    if len(school_en) > 50:
        return "Vedi descrizione"
    return school_en


def translate_subschool(subschool_en):
    """Translate a subschool name."""
    if not subschool_en:
        return None
    return SUBSCHOOL_MAP.get(subschool_en, subschool_en)


def main():
    with open("data/spells.json", encoding="utf-8") as f:
        spells = json.load(f)

    result = []
    missing = []

    for spell in spells:
        name_en = spell["name"]
        slug = spell["slug"]
        school_en = spell["school"]
        subschool_en = spell.get("subschool")

        # Normalize curly apostrophes to ASCII for lookup
        name_lookup = name_en.replace("\u2019", "'")
        name_it = NAME_MAP.get(name_lookup)
        if name_it is None:
            missing.append(name_en)
            name_it = name_en  # fallback to English

        school_it = translate_school(school_en)

        entry = {
            "slug": slug,
            "name": name_it,
            "school": school_it,
        }

        subschool_it = translate_subschool(subschool_en)
        if subschool_it is not None:
            entry["subschool"] = subschool_it

        result.append(entry)

    if missing:
        print(f"WARNING: {len(missing)} spells without Italian translation:")
        for m in missing:
            print(f"  - {m}")

    os.makedirs("data/i18n/it", exist_ok=True)
    with open("data/i18n/it/spells.json", "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    print(f"Written {len(result)} spell translations to data/i18n/it/spells.json")


if __name__ == "__main__":
    main()
